apiVersion: batch/v1
kind: Job
metadata:
  name: sample-app-tx
  namespace: mcm
  labels:
    app: sample-app-tx
spec:
  ttlSecondsAfterFinished: 1
  template:
    metadata:
      labels:
        app: sample-app-tx
    spec:
      restartPolicy: "Never"
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
        mcm-type: tx
      containers:
        - name: sample-app-tx
          image: mcm/sample-app:latest
          imagePullPolicy: Never
          workingDir: /opt/mcm/sdk/out/samples
          command: ["./sender_app"]
          args: ["-w", "1920", "-h", "1080", "-f", "30", "-s", "192.168.96.20", "-p", "10000", "-t", "st20", "-n", "3000"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MCM_MEDIA_PROXY_PORT
              value: "8002"
            - name: MCM_MEDIA_PROXY_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: memif-dir  # Using hostPath volume
              mountPath: /run/mcm  # Mount path in the pod
            - name: imtl-mgr  # Communicate with IMTL manager
              mountPath: /var/run/imtl  # Mount path in the pod
      volumes:
        - name: memif-dir  # Using hostPath volume
          hostPath:
            path: /tmp/mcm/memif
        - name: imtl-mgr
          persistentVolumeClaim:
            claimName: imtl-pvc
