version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: docker
    directory: /media-proxy
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: docker
    directory: /sdk
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: docker
    directory: /ffmpeg-plugin
    schedule:
      interval: "weekly"
      day: "sunday"
