# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024-2025 Intel Corporation
# Media Communications Mesh

LOG_FOLDER = "logs"
DEFAULT_OUTPUT_PATH = "/dev/null"

# time for establishing connection for example between TX and RX in st2110
MTL_ESTABLISH_TIMEOUT = 2
MCM_ESTABLISH_TIMEOUT = 5
DEFAULT_LOOP_COUNT = 7
MCM_RXTXAPP_RUN_TIMEOUT = MCM_ESTABLISH_TIMEOUT * DEFAULT_LOOP_COUNT
MAX_TEST_TIME_DEFAULT = 60

DEFAULT_MCM_FFMPEG_VERSION = "7.0"

MEDIA_PROXY_ERROR_KEYWORDS = ["[ERRO]"]
MESH_AGENT_ERROR_KEYWORDS = ["[ERRO]"]
RX_TX_APP_ERROR_KEYWORDS = ["[ERRO]"]

DEFAULT_MPG_URN = "ipv4:224.0.0.1:9003"
DEFAULT_REMOTE_IP_ADDR = "239.2.39.238"
DEFAULT_REMOTE_PORT = 20000
DEFAULT_PACING = "narrow"
DEFAULT_PAYLOAD_TYPE_ST2110_20 = 112
DEFAULT_PAYLOAD_TYPE_ST2110_30 = 111
DEFAULT_PIXEL_FORMAT = "yuv422p10le"
DEFAULT_RDMA_MAX_LATENCY_NS = 10000
