apiVersion: v1
kind: Namespace
metadata:
  name: mcm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memif-socket-fs
  namespace: mcm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: media-proxy
  namespace: mcm
  labels:
    app: media-proxy
spec:
  selector:
    matchLabels:
      app: media-proxy
  template:
    metadata:
      labels:
        app: media-proxy
    spec:
      nodeSelector:
        node-role.mcm.intel.com/worker: "true"
      containers:
        - name: media-proxy
          image: mcm/media-proxy:latest
          imagePullPolicy: Never
          command: [ "media_proxy" ]
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 2
              memory: 8Gi
              hugepages-2Mi: 1Gi
              hugepages-1Gi: 2Gi
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: memif-socket
              mountPath: /run/mcm
            - name: dev-vfio
              mountPath: /dev/vfio
            - mountPath: /hugepages-2Mi
              name: hugepage-2mi
            - mountPath: /hugepages-1Gi
              name: hugepage-1gi
            - mountPath: /dev/shm
              name: cache-volume
      volumes:
        - name: memif-socket
          persistentVolumeClaim:
            claimName: memif-socket-fs
        - name: dev-vfio
          hostPath:
            # Do not mount the top-level /dev/ directory for security reasons.
            # Instead mount a sub directory underneath the /dev/ directory, e.g. /dev/vfio/
            path: /dev/vfio
        - name: hugepage-2mi
          emptyDir:
            medium: HugePages-2Mi
        - name: hugepage-1gi
          emptyDir:
            medium: HugePages-1Gi
        - name: cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
