apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: media-proxy
  namespace: mcm
  labels:
    app: media-proxy
spec:
  selector:
    matchLabels:
      app: media-proxy
  template:
    metadata:
      labels:
        app: media-proxy
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: media-proxy
          image: mcm/media-proxy:latest
          imagePullPolicy: Never
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          command: [ "media_proxy" ]
          args: [ "-d", "kernel:eth0", "-i", $(POD_IP) ]
          resources:
            limits:
              cpu: 2
              memory: 8Gi
              hugepages-2Mi: 1Gi
              hugepages-1Gi: 2Gi
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 8001
              hostPort: 8001
              protocol: TCP
              name: grpc-port
            - containerPort: 8002
              hostPort: 8002
              protocol: TCP
              name: sdk-port
          volumeMounts:
            - name: memif-dir  # Using hostPath volume
              mountPath: /run/mcm  # Mount path in the pod
            - name: dev-vfio
              mountPath: /dev/vfio
            - mountPath: /hugepages-2Mi
              name: hugepage-2mi
            - mountPath: /hugepages-1Gi
              name: hugepage-1gi
            - mountPath: /dev/shm
              name: cache-volume
            - name: imtl-mgr  # Communicate with IMTL manager
              mountPath: /var/run/imtl  # Mount path in the pod
      volumes:
        - name: memif-dir  # Using hostPath volume
          hostPath:
            path: /tmp/mcm/memif
        - name: dev-vfio
          hostPath:
            # Do not mount the top-level /dev/ directory for security reasons.
            # Instead mount a sub directory underneath the /dev/ directory, e.g. /dev/vfio/
            path: /dev/vfio
        - name: hugepage-2mi
          emptyDir:
            medium: HugePages-2Mi
        - name: hugepage-1gi
          emptyDir:
            medium: HugePages-1Gi
        - name: cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
        - name: imtl-mgr
          persistentVolumeClaim:
            claimName: imtl-pvc
