# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mtl-pv
  namespace: mcm
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/var/run/imtl"
