# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imtl-pvc
  namespace: mcm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: imtl-pv
