name: Scan

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  hadolint:
    name: Hadolint
    runs-on: [self-hosted, Hadolint]
    steps:
      - uses: actions/checkout@v3
      - name: Hadolint Scan
        uses: intel-innersource/frameworks.devops.github.actions.hadolint@main
        with:
          recursive: true