name: build-docker

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  sdk-image-build:
    name: Build sdk Docker Image
    uses: ./.github/workflows/build_docker.yml
    with:
      docker_file_path:  "sdk/Dockerfile"
      docker_image_name: "sdk"

  ffmpeg-6-1-image-build:
    name: Build ffmpeg v6.1 Docker Image
    uses: ./.github/workflows/build_docker.yml
    with:
      docker_file_path:  "ffmpeg-plugin/Dockerfile"
      docker_image_name: "ffmpeg-6-1"
      docker_build_args: "FFMPEG_VER=6.1"

  ffmpeg-7-0-image-build:
    name: Build ffmpeg v7.0 Docker Image
    uses: ./.github/workflows/build_docker.yml
    with:
      docker_file_path:  "ffmpeg-plugin/Dockerfile"
      docker_image_name: "ffmpeg-7-0"
      docker_build_args: "FFMPEG_VER=7.0"

  media-proxy-image-build:
    name: Build Media-Proxy Docker Image
    uses: ./.github/workflows/build_docker.yml
    with:
      docker_file_path:  "media-proxy/Dockerfile"
      docker_image_name: "media-proxy"
