name: Linter
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the scans on"
        default: "main"
        type: string

permissions:
  contents: read
jobs:
  super-linter:
    name: "super-linter: Workflow initializing"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          ref: "${{ env.INPUT_BRANCH }}"

      - name: Lint
        uses: super-linter/super-linter/slim@e1cb86b6e8d119f789513668b4b30bf17fe1efe4 # v7.2.0 x-release-please-version
        env:
          DISABLE_ERRORS: false
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASH_SEVERITY: "warning"
          LINTER_RULES_PATH: ".github/configs"
          GITHUB_COMMENT_ON_PR: false
          GITHUB_STATUS_UPDATES: false
          VALIDATE_BASH_EXEC: true
          VALIDATE_BASH: true
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_CPP: true
          VALIDATE_GO: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GROOVY: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_JSONC_PRETTIER: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PROTOBUF: true
          VALIDATE_PYTHON_BLACK: true
          FILTER_REGEX_EXCLUDE: ^configs/
          VALIDATE_YAML_PRETTIER: true
