name: Trivy
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  checkout_code:
      runs-on: ubuntu-20.04
      name: Checkout code
      steps:
        - name: Harden Runner
          uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
          with:
            egress-policy: audit
        - name: Checkout code
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
  scan:
    runs-on: ubuntu-20.04
    needs: checkout_code
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    name: Scan Config
    steps:
      - name: Run Trivy vulnerability scanner for 'config'
        uses: aquasecurity/trivy-action@91713af97dc80187565512baba96e4364e983601 # master
        with:
          scan-type: 'config'
          hide-progress: false
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
      - name: Upload Trivy 'config' scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@b374143c1149a9115d881581d29b8390bbcbb59c # v3.22.11
        with:
          sarif_file: 'trivy-results.sarif'