name: Build SDK Dockerfile Ubuntu

on:
  pull_request:
    branches: [ "main", "dev", "maint-*" ]

permissions:
  contents: read

env:
  BUILD_TYPE: "Release"
  DOCKER_IMAGE_BASE: "ghcr.io/openvisualcloud/media-communications-mesh"
  DOCKER_IMAGE_TAG: "${{ github.sha }}"

jobs:
  docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0
        with:
          buildkitd-flags: --debug

      - name: Build and push SDK sample apps
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
        with:
          file: sdk/Dockerfile
          allow: network.host
          context: .
          push: false
          tags: "${{ env.DOCKER_IMAGE_BASE }}/sdk:${{ env.DOCKER_IMAGE_TAG }}"
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_BASE }}/sdk:buildcache
